version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: jwt_demo_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: jwt_demo_api
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/lumenalta_demo
      - JWT_SECRET=supersecret_change_me
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo_data:
